apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smackapi-v1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: smackapi
        version: v1
    spec:
      containers:
      - name: smackapi
        image: briarprivate.azurecr.io/chzbrgr71/smackapi:master-bb02b3e
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: acrregistrykey
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smackapi-v2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: smackapi
        version: v2
    spec:
      containers:
      - name: smackapi
        image: briarprivate.azurecr.io/chzbrgr71/smackapi:PR-9-eb0dce1
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: acrregistrykey